from .games.top_5_games import Top5GameList
from .games.bottom_5_games import Bottom5GameList
from .games.games_per_category import GamesPerCategoryList
from .games.more_than_5_players import MoreThan5PlayersList
from .games.most_reviewed_game import MostReviewedGameList
from .games.games_age_rec_under_8 import GamesAgeRecUnder8List
from .games.no_photo_count import NoPhotoCount
from .players.players_most_games import PlayerMostGames
from .players.players_most_reviews import PlayersMostReviews